# Generated by Django 5.0.6 on 2024-05-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime_ofpayment',
            new_name='datetime_of_payment',
        ),
    ]
